### ISSUE TITLE
Pre-trained model and training code release

### ISSUE THREAD

**Issue by oneThousand1000** [labhai/ffhq-wrinkle-dataset#6]
Hi!

Thank you very much for sharing this dataset! I find it really useful :)

Do you plan to release the pre-trained wrinkle detection model or the training code?

**Comment by ho-sick99** [comment]
Hello!

Thanks for your interest in our dataset. We're glad to hear that you find it useful.
Regarding your question, we certainly plan to make the pre-trained weights for wrinkle detection models (U-Net and SwinUNETR) publicly available.
We will work on preparing these resources and aim to release them as soon as possible. Thanks :)

**Comment by oneThousand1000** [comment]
Are there any updates :)?

**Comment by ho-sick99** [comment]
Hello!

Thank you very much for your patience, and I sincerely apologize for the delayed response. 
Our internal discussions regarding the public release of the code took longer than expected. 
We are pleased to let you know that we have now updated the repository with the pretrained weights and inference code for the wrinkle detection models.

We hope these resources will be helpful for your research or work :)

**Comment by oneThousand1000** [comment]
Thanks!
